// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgdglmsfhlzphoenglpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZGdsbXNmaGx6cGhvZW5nbHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzU2MzMsImV4cCI6MjA2MTA1MTYzM30.YNN8ADl38QcCnvSL3GsuGUApjdSCwEv9Me2g1yQNoGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);